### ISSUE TITLE
How to run this on chrome?

### ISSUE THREAD

**Issue by Winttgenstein** [kaliiiiiiiiii/brotector#2]
How to implement it? I tried it on chrome ran by nondriver, but it does not show anything unless I click inspect element or show page source on the html page, but it has the same outcome on other browsers that is not ran but bots.

**Comment by kaliiiiiiiiii** [comment]
Have you tested automated page interactions? Like clicking on the copy button or moving th mouse?
Please read the full Readme.md before opening an issue.

**Comment by Winttgenstein** [comment]
> Have you tested automated page interactions? Like clicking on the copy button or moving th mouse? Please read the full Readme.md before opening an issue.

I did, clicked accept cookies, scrolling, and open new tab etc.
